name: paisa
description: A expense manager app for Android, iOS, Web & Windows.

publish_to: 'none'

version: 3.1.1+31

environment:
  sdk: ">=3.0.0-136.0.dev <4.0.0"

dependencies: 
  animations: ^2.0.7
  chart_sparkline: ^1.0.12 
  csv: ^5.0.1
  dart_code_metrics: ^5.3.0
  date_picker_timeline: ^1.2.3 
  device_info_plus:  
  dynamic_color: ^1.5.4
  equatable: ^2.0.5
  file_picker: ^5.2.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_displaymode: ^0.5.0 
  flutter_localizations:
    sdk: flutter 
  flutter_svg: ^1.1.6
  get_it: ^7.2.0
  glassmorphism: ^3.0.0
  go_router: ^6.0.1
  google_fonts: ^3.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^0.8.6
  intl: '>=0.17.0 <0.19.0'
  material_color_utilities: ^0.2.0
  material_design_icons_flutter: ^6.0.7096
  package_info_plus: ^3.0.2
  path_provider: ^2.0.11
  permission_handler: ^10.2.0
  responsive_builder: ^0.4.3
  share_plus: ^6.3.0 
  url_launcher: ^6.1.7 
  url_strategy: ^0.2.0

dev_dependencies:
  build_runner: ^2.4.0
  flutter_lints: ^2.0.1 
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
